os:
  - linux
  - osx

sudo: false

language: go

go:
  - 1.9.x

before_install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

install:
  - make deps

script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)
  - go get -t ./...
  - ginkgo -v -randomizeAllSpecs -randomizeSuites -trace

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
